### ISSUE TITLE
NTLM hash for Lab 0

### ISSUE THREAD

**Issue by ymgh96** [stuxnet999/MemLabs#2]
Hello,
Please introduce a website that can crack the NTLM password (101da33f44e92c27835e64322d72e8b7) online!
I try multiple websites but, none of them can decrypt the gained password...

**Comment by cyb3rw0lf** [comment]
same problem here

**Comment by stuxnet999** [comment]
Hello @ymgh96 & @cyb3rw0lf ,

Yes, I am also not sure why this issue is coming up. Actually, this challenge that I made is 2 years old and I used [https://md5decrypt.net/en/Ntlm/](https://md5decrypt.net/en/Ntlm/ )for cracking the hash but it seems they have **refreshed** their database and this hash is no longer present.

That is the reason that I used Lab-0 as a sample challenge by providing the walkthrough.
